### ISSUE TITLE
Reminder: Your action items for ProtoSchool's new local leadership model

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/mumbai#2]
@indcoder 

As [announced](https://github.com/ProtoSchool/organizing/issues/84) in early March, ProtoSchool's new local leadership model centers around events as opposed to chapters and gives local event organizers more flexibility. If you haven't yet done so, there are a few steps you'll need to take as we transition to this new model, especially since it no longer relies on the use of GitHub.

**Tasks to complete by the end of April:**
- [x] Review the [updated local leadership model](https://github.com/protoschool/organizing), including the guidelines on what qualifies as a ProtoSchool workshop
- [x] Review the detailed [transition guide for chapter leaders](https://github.com/ProtoSchool/organizing/blob/master/COMMUNITY_MODEL_UPDATE.md)
- [x] Decide whether you'd like us to archive this chapter repo or transfer it to other ownership ([details here](https://github.com/ProtoSchool/organizing/blob/master/COMMUNITY_MODEL_UPDATE.md#phasing-out-chapter-listings-and-chapter-repos))
- [x] [Subscribe to the ProtoSchool newsletter](https://school.us4.list-manage.com/subscribe?u=41e9e493c56c3865870435d91&id=967f7cf514), checking the box for local leadership updates

If you have questions on the new local leadership model or your options as we transition, please feel free to [email us](mailto:protoschool@protocol.ai). 

Thank you so much for your continued community leadership!

**Comment by indcoder** [comment]
@terichadbourne  Please transfer the ownership of the Mumbai chapter to our community repo. 
https://github.com/HackerspaceMumbai

An email has also been sent to you regarding the same

Thank you.

**Comment by terichadbourne** [comment]
@indcoder Happy to take care of this but will need repo creation powers in the HackerspaceMumbai org in order to take care of it (assuming that's an org and not an individual account).

**Comment by indcoder** [comment]
Sorry for the delay @terichadbourne . You should have an invitation to join the organization with permissions to create public repos.

**Comment by terichadbourne** [comment]
I think I was successful @indcoder! This repo has been transferred!

**Comment by indcoder** [comment]
Thanks @terichadbourne . Got a confirmation notification email  from GitHub about repo transfer. Will confirm later in the night.
